### ISSUE TITLE
Approve/Disapprove of pages/posts

### ISSUE THREAD

**Issue by jordanddunn** [CosmoCMS/Cosmo#16]
- [ ] panel in sidebar for content requiring approval, show list similar to browse
- [ ] Users who don't have ability to schedule / post immediately or update pages when selecting any saving options (e.g. publish, update etc..) it should not publish but put up an alert that says "This post has been sent for approval.
- [ ] Allow certain Admin / moderators to be selected for approval of posts by categories of users ( #15 ).
- [ ] Notification management for posts that are being approved, allow quick approval/disapprove with a notes section, along with a link to the page. (see issue #15 )
- [ ] On the page editor it should show a notification at the top that says "This page is currently awaiting approval from {{username here}}" "Approve" "Disapprove" Which then opens the comments area for changes.
- [ ] When the user returns to their login, they should see the notification in their user area ( #15 ) which leads them to the page with comments related to it at the top of the page.
- [ ] After displaying the comment, it should show a button saying "Submit for Approval"
